[storage]
dsn = "designate:designate@tcp(localhost:3306)/designate"

[server]
address = ""
port = 5053
logquery = true

[influx]
user = "mdns"
password = "mdns"
host = "127.0.0.1:8086"
database = "mdns"

[logging]
# logging level can be one of "debug", "info", "warn" or "error"
level  = "info"
file   = "mdns.log"         # stdout to log to standard out, or syslog facility