[storage]
dsn = "designate:designate@tcp(localhost:3306)/designate"

[server]
address = ""
port = 5053
logquery = true

[influx]
user = "mdns"
password = "mdns"
host = "127.0.0.1:8086"
database = "mdns"

